# welcome to numpy

In [1]:
import numpy as np


In [2]:
myarr = np.array([[3,127,3]], np.int64) #we can define the data type of values
print(myarr)

[[  3 127   3]]


In [3]:
myarr[0,2] # to access array with locations
myarr.shape # to find dimension of array
myarr.dtype # to find the type of values stored in array

dtype('int64')

In [5]:
myarr[0,2]=35 # replacement of particular element
myarr

array([[  3, 127,  35]], dtype=int64)

# array creation methods

# Conversion from other Python structures


In [15]:
listarray = np.array([[1,2,3],[7,5,4],[9,6,3]])
listarray
listarray.dtype
#listarray.shape
listarray.size

9

# Intrinsic numpy array creation objects


In [18]:
zero = np.zeros((2,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
range = np.arange(15)
range1 = np.arange(1,14,.3) 
range1

array([ 1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7,  4. ,
        4.3,  4.6,  4.9,  5.2,  5.5,  5.8,  6.1,  6.4,  6.7,  7. ,  7.3,
        7.6,  7.9,  8.2,  8.5,  8.8,  9.1,  9.4,  9.7, 10. , 10.3, 10.6,
       10.9, 11.2, 11.5, 11.8, 12.1, 12.4, 12.7, 13. , 13.3, 13.6, 13.9])

In [30]:
lspace = np.linspace(1,20,10) #equally spaced 10 elements bw 1 and 20
lspace

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [37]:
emp = np.empty((2,5)) #create random array
emp

array([[ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444],
       [11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]])

In [39]:
emp_like = np.empty_like(range1)
emp_like

array([ 1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7,  4. ,
        4.3,  4.6,  4.9,  5.2,  5.5,  5.8,  6.1,  6.4,  6.7,  7. ,  7.3,
        7.6,  7.9,  8.2,  8.5,  8.8,  9.1,  9.4,  9.7, 10. , 10.3, 10.6,
       10.9, 11.2, 11.5, 11.8, 12.1, 12.4, 12.7, 13. , 13.3, 13.6, 13.9])

In [42]:
ide = np.identity(45) #identity matrix
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [43]:
ide.shape

(45, 45)

In [49]:
arr = np.arange(99) # to reshape array
arr = arr.reshape(3,33)

In [54]:
arr = arr.ravel() 
arr.shape

(99,)

# Axis


In [55]:
x= [[3,2,1],[6,7,8],[7,3,1]] 
x

[[3, 2, 1], [6, 7, 8], [7, 3, 1]]

In [57]:
ar = np.array(x)
ar

array([[3, 2, 1],
       [6, 7, 8],
       [7, 3, 1]])

In [59]:
ar.sum(axis=0) #addition downword

array([16, 12, 10])

In [60]:
ar.sum(axis =1) #addition of rows

array([ 6, 21, 11])

In [61]:
ar.T # transpose of array

array([[3, 6, 7],
       [2, 7, 3],
       [1, 8, 1]])

In [62]:
ar.flat

In [63]:
for item in ar.flat: #to get all the array elements 
    print(item)

3
2
1
6
7
8
7
3
1


In [67]:
ar.ndim #dimension of array
ar.size # size of array
ar.nbytes #no of bytes consumed by array

36

In [69]:
one = np.array([1,2,3,4,5,6,7])
one.argmax() #it gives index value where max is stored
one.argsort() # it returns array of locations in increasing order according to the sorting of array items

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [72]:
ar

array([[3, 2, 1],
       [6, 7, 8],
       [7, 3, 1]])

In [82]:
ar.argmin() # firstly it flates the array and then find the index where min value is stored
ar.argmax()# same as find min
ar.argmin(axis=1) #find in axis =1
ar.argmin(axis=0)#find in axis = 0
ar.argsort(axis=1)
ar.ravel()
ar.reshape(9,1)

array([[3],
       [2],
       [1],
       [6],
       [7],
       [8],
       [7],
       [3],
       [1]])

In [87]:
ar2 = np.array([[1,2,7],[4,3,8],[8,5,2]])

In [86]:
ar

array([[3, 2, 1],
       [6, 7, 8],
       [7, 3, 1]])

In [88]:
ar2+ar

array([[ 4,  4,  8],
       [10, 10, 16],
       [15,  8,  3]])

In [89]:
np.sqrt(ar) #square root

array([[1.73205081, 1.41421356, 1.        ],
       [2.44948974, 2.64575131, 2.82842712],
       [2.64575131, 1.73205081, 1.        ]])

In [90]:
ar.sum()

38

In [91]:
ar.max()

8

In [95]:
np.where(ar>5)

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [93]:
ar

array([[3, 2, 1],
       [6, 7, 8],
       [7, 3, 1]])

In [96]:
np.count_nonzero(ar)

9

In [98]:
import sys
ch_ar = [0,3,54,6]
np_ar = np.array(ch_ar)
sys.getsizeof(1)*len(ch_ar)

112

In [100]:
np_ar.itemsize * np_ar.size

16